### ISSUE TITLE
Add folder structure

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [commclassroom/assets#1]
Adding `logo`, `community graphics`, etc folders. And shifting all the images to its a particular folder.

**Comment by rwiteshbera** [comment]
@kaiwalyakoparkar Can you please assign me this issue?

**Comment by deeksha-singh030** [comment]
I'm interested to work on this issue @kaiwalyakoparkar

**Comment by AsswinCR** [comment]
@kaiwalyakoparkar can i work on this?

**Comment by saksham-s1ngh** [comment]
Has this issue been resolved or can I still be assigned to this issue?

**Comment by kaiwalyakoparkar** [comment]
@rwiteshbera Go ahead with the issue, I will assign it to you shortly

**Comment by vivek9386** [comment]
I want to work on this issue, i can be assigned for this?

**Comment by SahityaRoy** [comment]
> Adding `logo`, `community graphics`, etc folders. And shifting all the images to its a particular folder.

I want to work on this
